spring.datasource.url=jdbc:mysql://localhost:3306/universitybank?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=your_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT Configuration
bank.app.jwtSecret=SecretKey1234567890
bank.app.jwtExpirationMs=86400000
spring.security.user.name=admin
spring.security.user.password=123456
